### ISSUE TITLE
Not possible to sign the CLA

### ISSUE THREAD

**Issue by gabrielbussolo** [openfga/.github#13]
I noticed that is not possible to sign the CLA before submit a pull request.

When clicking on the link as said on
https://github.com/openfga/.github/blob/a5234dc990debe01ebf7327cfd853375e8e52846/CONTRIBUTING.md?plain=1#L63C92-L63C92
The following screen is prompted
![Screenshot 2023-08-06 at 01 02 51](https://github.com/openfga/.github/assets/4117683/a44b3710-51c9-45b1-8eae-30dfcd8bb7a2)
without any option.

maybe is because we are using the linux foundation easy cla such as  
https://github.com/openfga/cli/pull/121#issuecomment-1666620349
instead of the cla assistant

**Comment by aaguiarz** [comment]
Thanks @gabrielbussolo! We updated the contributing guide to point to EasyCLA.
